version: "3.8"
services:
  tomcat-service:
    build: .
    container_name: tomcat_application
    restart: on-failure
    ports:
      - 8080:8080
    depends_on:
      db-service:
        condition: service_healthy

    environment:
      - WAIT_HOSTS=db-service:5432
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-service:5432/users_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

  # Database
  db-service:
    image: postgres:16-alpine
    container_name: db-service
    restart: always
    volumes:
      - /var/lib/postgresql/data/
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    ports:
      - 6580:5432
    # переменные окружения
    environment:
      POSTGRES_DB: users_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
